# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    compose.yaml                                       :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: migarci2 <migarci2@student.42malaga.com    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/08/29 16:03:17 by migarci2          #+#    #+#              #
#    Updated: 2024/08/29 18:16:58 by migarci2         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

services:

  # Servicios de infraestructura
  rabbitmq:
    image: rabbitmq:4.0.1-management
    restart: always
    ports:
      - "5672"
      - "15672:15672"
    env_file: .env

  redis:
    image: redis:7.4.2
    restart: always
    ports:
      - "6379"

  consistency:
    build:
      context: consistency
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - rabbitmq

  api-gateway:
    build:
      context: api-gateway
      dockerfile: Dockerfile
    ports:
      - "5443:443"
      - "5081:80"

  auth:
    build:
      context: auth
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    env_file:
      - .env
      - auth/service/.env
    volumes:
      - auth-data:/var/lib/postgresql/data
    depends_on:
      - rabbitmq

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "5080:80"
    volumes:
      - ./frontend/service:/var/www/service
    depends_on:
      - auth

  social:
    build:
      context: social
      dockerfile: Dockerfile
    ports:
      - "5051:5051"
    env_file:
      - .env
      - social/service/.env
    volumes:
      - social-data:/var/lib/postgresql/data
    depends_on:
      - auth

  pong:
    build:
      context: pong
      dockerfile: Dockerfile
    ports:
      - "5052:5052"
    env_file:
      - .env
      - pong/service/.env
    volumes:
      - pong-data:/var/lib/postgresql/data
    depends_on:
      - auth
  chess:
    build:
      context: chess
      dockerfile: Dockerfile
    ports:
      - "5053:5053"
    env_file:
      - .env
      - chess/service/.env
    volumes:
      - chess-data:/var/lib/postgresql/data
    depends_on:
      - auth

  notifications:
    build:
      context: notifications
      dockerfile: Dockerfile
    ports:
      - "5054:5054"
    env_file:
      - .env
      - notifications/service/.env
    volumes:
      - notifications-data:/var/lib/postgresql/data
    depends_on:
      - auth

networks:
  ft_transcendence-network:
    driver: bridge

volumes:
  auth-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volume-data/auth

  social-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volume-data/social

  pong-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volume-data/pong

  chess-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volume-data/chess

  notifications-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volume-data/notifications
