# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    compose.yaml                                       :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: migarci2 <migarci2@student.42malaga.com    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/08/29 16:03:17 by migarci2          #+#    #+#              #
#    Updated: 2024/08/29 18:16:58 by migarci2         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

services:

  # Infrastructure services
  rabbitmq:
    image: rabbitmq:4.0.1-management
    restart: always
    ports:
      - 5672
      - 15672:15672
    env_file: .env

  api-gateway:
    build:
      context: api-gateway
      dockerfile: Dockerfile
    ports:
      - 5443:443
      - 5081:80

  auth:
    build:
      context: auth
      dockerfile: Dockerfile
    ports:
      - 5050:5050
    env_file:
      - .env
      - auth/service/.env

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 5080:80
    volumes:
      - ./frontend/service:/var/www/service

  #social:
  #  build:
  #    context: social
  #    dockerfile: Dockerfile
  #  ports:
  #    - 5051:5001
  #  env_file:
  #    - .env
  #    - social/service/.env
  #  # depends_on:
  #  #   - redis
  #  volumes:
  #    - social-data:/var/www/service

    # redis:
    #   container_name: redis_cont
    #   image: redis:7.4-alpine
    #   expose:
    #     - "6379"
    #   networks:
    #     - red
    #   restart: always
    #   command: redis-server

  #chess:
  #  build:
  #    context: chess
  #    dockerfile: Dockerfile
  #  ports:
  #    - 5052:5002
  #  env_file:
  #    - .env
  #    - chess/service/.env
  #  volumes:
  #    - chess-data:/var/www/service

networks:
  ft_transcendence-network:
    driver: bridge

volumes:
  auth-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volume-data/auth

  social-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volume-data/social

  pong-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volume-data/pong

  chess-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volume-data/chess
