# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    compose.yaml                                       :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: migarci2 <migarci2@student.42malaga.com    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/08/29 16:03:17 by migarci2          #+#    #+#              #
#    Updated: 2024/08/29 18:16:58 by migarci2         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

services:

  # Infrastructure services
  rabbitmq:
    image: rabbitmq:4.0.1-management
    restart: always
    ports:
    - 5672
    - 15672:15672
    env_file: .env

  api-gateway:
    build:
      context: api-gateway
      dockerfile: Dockerfile
    ports:
    - 443:443
    - 80:80

  auth:
    build:
      context: auth
      dockerfile: Dockerfile
    ports:
      - 5000
    env_file:
      - .env
      - auth/service/.env

  fronted:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 80

networks:
  ft_transcendence-network:
    driver: bridge

volumes:
  auth-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volume-data/auth

  social-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volume-data/social

  pong-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volume-data/pong

  chess-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volume-data/chess
