services:
  chat_online:
    container_name: chat_online_cont
    build: ./dockers/mywebsite
    env_file:
      - .env
    volumes:
      - chat:/mywebsite
      - db:/var/lib/postgresql/data
    networks:
      - red
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: always
  redis:
    container_name: redis_cont
    image: redis:7.4-alpine
    expose:
      - "6379"
    networks:
      - red
    restart: always
    command: redis-server

networks:
  red:
    driver: bridge

volumes:
  chat:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './mywebsite/'
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './db/'