# Generated by Django 5.1.1 on 2024-10-08 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=20, verbose_name='Group Name')),
                ('room_code', models.CharField(max_length=50, unique=True, verbose_name='Room Code')),
                ('public', models.BooleanField(default=False, verbose_name='Public Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, unique=True, verbose_name='Username')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300, verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.groups', verbose_name='Group ID')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.users', verbose_name='Sender ID')),
            ],
        ),
        migrations.CreateModel(
            name='Group_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.groups', verbose_name='Group ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.users', verbose_name='User ID')),
            ],
        ),
        migrations.CreateModel(
            name='Direct_messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.messages', verbose_name='Receiver ID')),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='chat.users', verbose_name='Receiver ID')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='chat.users', verbose_name='Sender ID')),
            ],
        ),
    ]
