# Generated by Django 5.1.1 on 2024-10-08 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_groups_users_messages_group_users_direct_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
        migrations.RenameModel(
            old_name='Group_users',
            new_name='Group_user',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
